service: pet-adopter-api

custom:
  params:
    usersTableName: ${ssm:/petAdopter/${opt:stage, 'dev'}/table/users/name}
    usersTableArn: ${ssm:/petAdopter/${opt:stage, 'dev'}/table/users/arn}
    petsTableName: ${ssm:/petAdopter/${opt:stage, 'dev'}/table/pets/name}
    petsTableArn: ${ssm:/petAdopter/${opt:stage, 'dev'}/table/pets/arn}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USERS_TABLE_NAME: ${self:custom.params.usersTableName}
    PETS_TABLE_NAME: ${self:custom.params.petsTableName}
    SECRET: 'c7aaa047d2e72b49c602a8917faaca7f'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:GetRecords'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:PutItem'
      Resource:
        - ${self:custom.params.usersTableArn}/*
        - ${self:custom.params.usersTableArn}
        - ${self:custom.params.petsTableArn}

plugins:
  - serverless-offline

functions:
  app:
    handler: src/index.handler
    timeout: 30
    events:
      - http:
          path: /auth/signin
          method: POST
          cors: 
            origin: "*"
      - http:
          path: /auth/signup
          method: POST
          cors: 
            origin: "*"
      - http:
          path: /pet
          method: POST
          cors: 
            origin: "*"
      - http:
          path: /pet
          method: GET
          cors: 
            origin: "*"
      - http:
          path: /pet/{id}
          method: PUT
          cors: 
            origin: "*"
      - http:
          path: /pet/{id}
          method: DELETE
          cors: 
            origin: "*"
      - http:
          path: /pet/{id}
          method: GET
          cors: 
            origin: "*"
      - http:
          path: /user
          method: GET
          cors: 
            origin: "*"
      - http:
          path: /user/{id}
          method: PUT
          cors: 
            origin: "*"
      - http:
          path: /user/{id}
          method: DELETE
          cors: 
            origin: "*"
      - http:
          path: /user/{id}
          method: GET
          cors: 
            origin: "*"

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - src/**
